### ISSUE TITLE
Change the path from where the images are served

### ISSUE THREAD

**Issue by Roxeen12** [awcodes/filament-curator#10]
I'm trying to use the media picker and the images are stored in storage/app/public/media. I've created another folder for those images in public/assets and I want to get them from there. Is there any way to do that?

File URL from the dashboard: http://127.0.0.1:8000/storage/media/6ab0b41f-8fba-406f-a652-2a5572a0554c.png

**Comment by awcodes** [comment]
The disk and directory can be set in the config file. 

I'd recommend not using the actual public directory for this, but it can be done by setting up the public directory as a 'disk'. There are several tutorials on this available through a Google search.

Currently all assets get saved to the same place as defined by the 'disk' and 'directory' settings in the config. It is on the roadmap to make this more configurable on a field by field basis.
