### ISSUE TITLE
Glide server without secure

### ISSUE THREAD

**Issue by lotarbo** [awcodes/filament-curator#101]
Hello, right now by default, everyone can spoof glide server with mass image transformation.
I think better add signature to glide server https://glide.thephpleague.com/1.0/config/security/

**Comment by awcodes** [comment]
You are free to provide your own implementation of Glide server via Curator's global settings.

`->glideServer(Server|ServerFactory)`

**Comment by lotarbo** [comment]
@awcodes i think it's related to `MediaController` we need to check signature in show method

**Comment by awcodes** [comment]
Yep, you're right. I'll see what I can do. thanks.

**Comment by awcodes** [comment]
Thanks for bringing this to my attention. It's been added to v2.1.0.
