### ISSUE TITLE
Could not install on new laravel 10 

### ISSUE THREAD

**Issue by naramwork** [awcodes/filament-curator#110]
When I try to install this package using the new laravel 10 
it shows this message : 
  Problem 1
    - Root composer.json requires awcodes/filament-curator 2.1.2 -> satisfiable by awcodes/filament-curator[v2.1.2].
    - awcodes/filament-curator v2.1.2 requires illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.0] but these were not loaded, likely because it conflicts with another require.

**Comment by howdu** [comment]
I'm sure @awcodes will release a new version soon but for now you can use the dev version
```bash
composer require awcodes/filament-curator "^2.0-dev"
```

You will also need `"minimum-stability": "dev"` in your composer.json file.
