### ISSUE TITLE
RTL mode

### ISSUE THREAD

**Issue by ihahachi** [awcodes/filament-curator#117]
The padding or margin display is problematic when using RTL mode.

![image](https://user-images.githubusercontent.com/7762172/222291244-2948b587-2732-4e0f-a223-3c375549af6e.png)

**Comment by awcodes** [comment]
Did you mean to post this to curator? That's not a part of curator.

**Comment by awcodes** [comment]
This was fixed in the latest release of Quick Create plugin.

**Comment by ihahachi** [comment]
Sorry, I posted this issue in the wrong repository. I meant Quick Create plugin. 
Anyway, thanks for fixing the issue.
