### ISSUE TITLE
fitContent does not exist

### ISSUE THREAD

**Issue by lotarbo** [awcodes/filament-curator#118]
Hello. Docs says that i can use fitContent, but method doesn't exist.
Also without fit some images look bad
![image](https://user-images.githubusercontent.com/1766890/222444415-7e4440dd-3508-40d8-93fb-b3287c5b49fc.png)
and this is original image
![image](https://user-images.githubusercontent.com/1766890/222444534-649ce65a-79db-46eb-9c8e-325cdf0afeff.png)

**Comment by awcodes** [comment]
Sorry, about that it was an error in the readme.

Should be `->constrained()`
