### ISSUE TITLE
Rotation bug on curation

### ISSUE THREAD

**Issue by archilex** [awcodes/filament-curator#123]
I'm encountering a rotation bug when creating curation. There may be multiple ways to reproduce this, but what causes it for me is:

1. Take a picture with an iPhone in portrait orientation. 
2. Upload the picture to Curator. (Picture is oriented correctly).
3. Create a curation (Picture is oriented correctly in the preview, but note that Cropper set 90 in the rotation)
4. Save the curation. The curation is upside down.

From what I can tell Cropper is getting the 90 degree rotation from the EXIF data and sets this in the curation form. However when calling `saveCuration` the original image is loaded without the orientation correction and then it's rotated AGAIN since a 90 rotation was set by cropper.

In `saveCuration` you can call `$image->orientate()` before `->rotate()` which orients the image per the EXIF date, HOWEVER it still applies Cropper's 90 degree rotation so the image will be on it's side.

As of now a workaround is to export the image using an app like Preview before uploading. Exporting the image will "bake in" the orientation preventing the bug. 

Emailing the image to yourself is NOT a workaround. The iPhone will convert the HEIC into a JPG, but the EXIF data will still be attached.

**Comment by awcodes** [comment]
Interesting. I would have expected cropper to handle it. 

Thanks. I'll look into it.

**Comment by awcodes** [comment]
Thanks for the heads up this is fixed in v2.2.7

**Comment by archilex** [comment]
Awesome! Great work! The discussions and workarounds for this topic are crazy. Nice solution. Thanks!
