### ISSUE TITLE
Curation tab image size on load

### ISSUE THREAD

**Issue by martinmildner** [awcodes/filament-curator#142]
hi @awcodes,

When I click on the "Curation" tab, sometimes the image isn't displayed in full size. Once I change the size of the browser, the view adjusts. Does this happen to you as well? 

Video: https://user-images.githubusercontent.com/789541/226858123-e0b817f1-c8db-4ecc-ab4e-95c8f4f4e41b.mp4
Tested with Safari (Version 16.0) and Firefox (Version 111.0.1)

Greetings,
martin

**Comment by awcodes** [comment]
Hey Martin,

This is a known bug that I'm still working through. I've tracked it down to being a race condition where the cropperjs script initializes before the image has finished loading. Seems to happen with larger file size images and/or slower connections. Haven't been able to consistently isolate it yet though.

Hope to have it figured out soon.
