### ISSUE TITLE
CuratorPicker Not Working When Called From a Modal

### ISSUE THREAD

**Issue by adityaa-codes** [awcodes/filament-curator#150]
Hi i have a create form page in which i have added, createOptionsForm in some Select fields , on clicking on them it opens modal to create dependent Data,
On Opening Model, i have a field to add media using Curator to the dependent data, is there any way i can open nested modals.
Currently its not working, its just give me blank page

Create Data Page

![image](https://user-images.githubusercontent.com/26678129/228534644-d09c097b-c193-422e-8c03-fa877b0957be.png)

Create Dependent Modal Page
![image](https://user-images.githubusercontent.com/26678129/228534718-3e97a3ac-1da9-4c14-b610-2b9fda492358.png)

On Clicking On Add Media
![image](https://user-images.githubusercontent.com/26678129/228534913-d0800365-9c67-4e79-a2e8-bc54afe22e18.png)

**Comment by awcodes** [comment]
Hmm. Would you happen to have a reproduction repo I could clone? I know it works in modals, but this could be a conflict with suffixActions since they use the same hooks to mount an action.

**Comment by adityaa-codes** [comment]
i'll create a repo in sometime and share the link here, thank you

**Comment by awcodes** [comment]
No need for the repo. This is a conflict with form component actions and not being able to support nested modals in Filament. 

I am working on a solution and will keep you posted.

**Comment by adityaa-codes** [comment]
Awesome, Thank you so much for this library and the efforts, Appreciated 🙌🏻

**Comment by awcodes** [comment]
Haven't forgotten about this. Just a really hard problem to solve. Hang in there.

**Comment by adityaa-codes** [comment]
Haha, its already cool that you've made such an awesome tool,
Take as much time as you need. I'll try to deep dive myself, trying to improve my TALL Skills

**Comment by awcodes** [comment]
Thank you for the kind words and the understanding. Filament V3 should make this a lot better.

**Comment by adityaa-codes** [comment]
Eagerly waiting for Filament V3

**Comment by awcodes** [comment]
This has been solved in v3. Hang in there.

**Comment by adityaa-codes** [comment]
When we can expect v3 to release, after livewire v3 right?

**Comment by awcodes** [comment]
Yep. Can't launch without livewire.
