### ISSUE TITLE
acceptedFileTypes should not let you pick another file type

### ISSUE THREAD

**Issue by lotarbo** [awcodes/filament-curator#157]
I have field with `acceptedFileTypes(['image/jpeg', 'image/png'])` and I can't upload any other file type, but I can pick any file from already uploaded. I can pick mp4 video for this field.

**Comment by alanablett** [comment]
Hi @awcodes I'm not sure if this one is totally fixed? I Was still able to select previously uploaded files when using the `acceptedFilesTypes` argument on my `CuratorPicker` field.

I was taking a look through the code for the curator panel component and saw that the `getFiles` method actually uses a property called `types` to check for file types. So I went ahead and created an override of `vendor/awcodes/filament-curator/resources/views/components/actions/picker-action.blade.php` locally and passed through the `acceptedFilesTypes` but passed them through to the `types` property. This seems to work as expected. However I didnt know if there was a specific reason you'd done it in the way you have. My `picker-action.blade.php` looks like this

```html
<livewire:curator-panel
    :accepted-file-types="$acceptedFileTypes"
    :types="$acceptedFileTypes" // copy of the acceptedFileTypes
    :disk-name="$diskName"
    :directory="$directory"
    :image-crop-aspect-ratio="$imageCropAspectRatio"
    :image-resize-mode="$imageResizeMode"
    :image-resize-target-width="$imageResizeTargetWidth"
    :image-resize-target-height="$imageResizeTargetHeight"
    :is-limited-to-directory="$isLimitedToDirectory"
    :is-multiple="$isMultiple"
    :max-items="$maxItems"
    :max-width="$maxWidth"
    :min-size="$minSize"
    :max-size="$maxSize"
    :modal-id="$modalId"
    :path-generator="$pathGenerator"
    :rules="$rules"
    :selected="$selected ?? []"
    :should-preserve-filenames="$shouldPreserveFilenames"
    :state-path="$statePath"
    :visibility="$visibility"
/>
```

**Comment by awcodes** [comment]
Are you on v2 or v3 of the plug-in? It does work on v2. Unless I'm misunderstanding what issue you're having.

**Comment by alanablett** [comment]
> Are you on v2 or v3 of the plug-in? It does work on v2. Unless I'm misunderstanding what issue you're having.

I'm using `awcodes/filament-curator:3.0.0` and `filament/filament:3.0.41`

I just went ahead and created a test project using `awcodes/filament-curator:2.10.1` and `filament/filament:2.17.53` and can confirm that the `acceptedFileTypes` array does work as expected. The list of available files is filtered down to just the types that I specify on the field. So it looks like a v3 specific issue.

**Comment by awcodes** [comment]
Ok. I'll get it corrected as soon as I can. Thank you.

**Comment by alanablett** [comment]
> Ok. I'll get it corrected as soon as I can. Thank you.

Thank you so much for the awesome plugin 👏👏
