### ISSUE TITLE
Upload breaks on Images with exif Encoding Issues

### ISSUE THREAD

**Issue by derteaser** [awcodes/filament-curator#167]
Hi!
I have an issue with some images that seem to contain malformed exif data. Whenever these are uploaded, the process breaks and returns the following:
```php
Illuminate\Database\Eloquent\JsonEncodingException: Unable to encode attribute [exif] for model [Awcodes\Curator\Models\Media] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded.
```

Expected behavior would be that the exif data gets fixed or thrown away with a warning instead of making it impossible to upload the image.

This is one of the images that breaks the upload:
![CDBCAB70-EF98-49AC-BFA0-55805C0AC383](https://user-images.githubusercontent.com/406951/233998333-9cd8ce8d-1fb7-4bb6-9914-86ab32fa75ea.jpeg)

**Comment by howdu** [comment]
@derteaser Please try with the above fix.

**Comment by derteaser** [comment]
@howdu I tried your fix with two images that broke the upload before. Both now uploaded smoothly and I can see exif data in Filament. Thanks a lot!
