### ISSUE TITLE
Builder methods in Curator facade yield editor warning

### ISSUE THREAD

**Issue by machacekmartin** [awcodes/filament-curator#169]
After installing package with `composer require awcodes/filament-curator` and  `php artisan curator:install`, I want to change global settings (f.e. maximum size).

Tutorial suggests to use builder methods on `Awcodes\Curator\Facades\Curator` facade. 

When I use `Curator:maxSize(2000)` I receive a warning from Intelephense:

![image](https://user-images.githubusercontent.com/33912290/234992562-083013ee-79c0-42e8-9fbf-c7b021f59187.png)

My guess is that while docblock successfully translates facade method `* @method static maxSize(int|Closure $size)` into `static` method, it fails to recognize the real return type -- `static`, resulting in the warning above. 

I suggest adding a second `static` keyword to these builder methods to imply real return type:

`* @method static static maxSize(int|Closure $size)` 

> same approach as in `Carbon\Traits\Comparison`

**Comment by awcodes** [comment]
Must be an intelephense thing. Works fine in phpStorm. Either way will be updated in next release.
