### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by caendesilva** [awcodes/filament-curator#18]
Hey! This package looks amazing, and it would be neat to be able to use components from it. However, since there is no license file attached, no-one is allowed to use the code herein. https://choosealicense.com/no-permission/

I would suggest the MIT License, as that's what both Laravel and FilamentPHP uses.

All the best, Caen

**Comment by MACscr** [comment]
While the file is indeed missing, it says in the README that it is MIT licensed. its at the bottom.

**Comment by awcodes** [comment]
As @MACscr said. It is MIT. And is still under development. I will worry about this as it gets closer to v1. But even then it will continue to be MIT.
