### ISSUE TITLE
generateThumbs being called on non-image types

### ISSUE THREAD

**Issue by jeffgreco13** [awcodes/filament-curator#2]
Within the created closure on the Media model, self::generateThumbs($media) is being called even if the mimetype is not an image (ie. PDF). This causes a fatal error with Intervention. Possible fix:

```php
                static::created(function (Media $media) {
			$media->refresh();
			if (str($media->type)->contains("image")) {
				self::generateThumbs($media);
			}
		});
```

**Comment by awcodes** [comment]
This has been released in https://github.com/awcodes/filament-curator/releases/tag/v0.2.5
