### ISSUE TITLE
Error after change from pdf file to image and vice versa

### ISSUE THREAD

**Issue by valpuia** [awcodes/filament-curator#239]
[Screencast from 07-07-2023 10:16:12 AM.webm](https://github.com/awcodes/filament-curator/assets/28250303/b325b958-c63c-40f9-b6c7-c16a21e5f0ae)

Error message: `Filament\Forms\Components\BaseFileUpload::Filament\Forms\Components\{closure}(): Argument #1 ($file) must be of type Livewire\TemporaryUploadedFile|string, array given`

How to reproduce:
1. Upload new PDF file
2. Edit file and "Upload new" tab, change it to Image
3. After save go to "Curator" tab
4. Create curator and save (from edit page)

The problem is gone after page refresh

**Another Problem**
[Screencast from 07-07-2023 10:32:36 AM.webm](https://github.com/awcodes/filament-curator/assets/28250303/223e7b54-cc1e-4333-8188-1b668b1103f9)

How to reproduce:
1. Upload new Image file
2. Edit file and "Upload new" tab, change it to PDF
3. Save
4. Try to remove from "Upload new" tab page

**Comment by awcodes** [comment]
Hmm. It's not really meant to be a file converter. I would think that when uploading a completely different file / mine type. You'd just upload a new file.

**Comment by valpuia** [comment]
> I would think that when uploading a completely different file / mine type. You'd just upload a new file.

I don't understand this part.. my english is not great.
But we can upload different file (different mime type) while editing also.. like I said in the OP "The problem gone after page refresh" may be we need to refresh manually :rofl:

**Comment by awcodes** [comment]
What I'm getting at is the use case for swapping an image with a pdf, csv, or excel file. or vise versa. Definitely, something needs to be addressed here. Just trying to figure out what exactly.
