### ISSUE TITLE
When calling multiple CuratorPicker::make on the same for, the page crashes

### ISSUE THREAD

**Issue by matt-shirey** [awcodes/filament-curator#241]
Whenever I add multiple `CuratorPicker::make` to my form, it causes the form to throw an error.

Code:
```php
use Awcodes\Curator\Components\Forms\CuratorPicker;

CuratorPicker::make('thumbnail')
    ->label('Thumbnail Image')
    ->disk('local')
    ->directory('selections'),
CuratorPicker::make('main_image')
    ->label('Main Image')
    ->disk('local')
    ->directory('selections'),
```

Error:
`Awcodes\Curator\Components\Forms\CuratorPicker::Awcodes\Curator\Components\Forms\{closure}(): Argument #2 ($state) must be of type array|int|null, string given, called in...`

**Comment by awcodes** [comment]
One of your fields is returning a string instead of a media record or media record id. You'll need to debug further to see why that is.

**Comment by matt-shirey** [comment]
@awcodes Thank you.  I missed that the field had old data in it.

**Comment by matt-shirey** [comment]
@awcodes Thank you. I missed that the field had old data in it.
