### ISSUE TITLE
Cannot unlink image using picker

### ISSUE THREAD

**Issue by phpsa** [awcodes/filament-curator#242]
I have a form with an image attached,
if i use the remove option, it clears on the display, however it does not remove the relationship, and as such on form reload, the image is re-attached,.

![image](https://github.com/awcodes/filament-curator/assets/952595/32bd3ef0-53cd-4483-b251-917cf32177d0)

on some debugging, it looks like the afterStateUpdated is working as expected, however when saving the form, it is reloading the relationship from the model and re-populating, in the `dehydrateStateUsing` method, state is repopulated & oldState shows blank as expected.

**Comment by awcodes** [comment]
It's not going to remove the relationship until the record is saved. 

Is this on v2?

**Comment by phpsa** [comment]
this is on v2 yes, this is after saving, it does not remove the record on saving as the save endpoint seems to reload the original record and repopulate it.

**Comment by awcodes** [comment]
Ok, thanks, I'll look into it as soon as I get a chance.

**Comment by awcodes** [comment]
This should be fixed with v2.8.4. Let me know if it's still an issue.

Thanks.
