### ISSUE TITLE
Large image upload bug

### ISSUE THREAD

**Issue by pinkertoon** [awcodes/filament-curator#246]
Hi!
When I'm trying to upload image >~2.5mb via CuratorPicker field my form starts endless reload(like reactive field updated). Video and images that breaks form attached. My form code below. When I'm removing "_relationship('hashtags', 'title')_ " & " _multiple()_" everything works fine. 
Using Curator v2.8.3
PHP 8.1
Video link: https://drive.google.com/file/d/1rplcfZtQ1O_8nrYL6oprPfeb8yduIQHq/view
Some thoughts:
1. After clearing image exif metadata - everything works fine. 
2. If I go to vendor/awcodes/filament-curator/src/Components/Modals/CuratorPanel.php  in function **addFiles()** and set $item['exif'] = null - everything works normal. Edited file:
```
public function addFiles(): void
    {

        $media = [];

        foreach ($this->addMediaForm->getState()['files'] as $item) {
            // Fix malformed utf-8 characters
            if (! empty($item['exif'])) {
                array_walk_recursive($item['exif'], function (&$entry) {
                    if (! mb_detect_encoding($entry, 'utf-8', true)) {
                        $entry = utf8_encode($entry);
                    }
                });
            }
            $item['exif'] = null;
            $media[] = Curator::getMediaModel()::create($item);
        }

        $this->addMediaForm->fill();
        $this->dispatchBrowserEvent('new-media-added', ['media' => $media]);
    }
```

My form code:
```
public static function form(Form $form): Form
    {
        return $form
            ->schema([
                        Select::make('hashtag_id')
                            ->relationship('hashtags', 'title')
                            ->options(Hashtag::all()->pluck('title', 'id'))
                            ->label(__('filament::resources/pages/form-element.hashtags'))
                            ->searchable()
                            ->preload()
                            ->multiple()
                            ->createOptionForm([
                                Tabs::make('tabs')
                                    ->tabs(HashtagResource::getFormLocalizationElement())
                                    ->columnspan([
                                        'sm' => 2,
                                    ])
                                ])
                            ->columnSpan([
                                'sm' => 1,
                            ]),
                        Toggle::make('is_slider')
                            ->label(__('filament::resources/pages/form-element.is_slider'))
                            ->default(false)
                            ->required()
                            ->hidden(fn(Closure $get) => !$get('is_slider_menu'))
                            ->inline(true)
                            ->columnSpan([
                                'sm' => 2,
                            ]),
                        CuratorPicker::make('main_picture_id')
                            ->label(__('filament::resources/pages/form-element.main_image'))
                            ->columnSpan([
                                'sm' => 2,
                            ]),
               ]);
    }
```
![bugged image 2](https://github.com/awcodes/filament-curator/assets/69795585/2da1c156-52bf-49b7-8767-072c2a4553ad)
![bugged image 1](https://github.com/awcodes/filament-curator/assets/69795585/c8868153-8313-4fa6-ac24-9964e6b9a521)

**Comment by howdu** [comment]
Are you getting any errors added to your logs? Wondering if it's maxing out the TEXT column's maximum length of 65,535 characters. 

When I testing your images it working fine for me but Github might of altered the EXIF data. 

Can you please try saving the output of `$item['exif']` to a text file before you set it to null and attach that here so we can see the contents?

**Comment by pinkertoon** [comment]
On my side bug appears with every image > 2.5mb (localhost & test server), i compressed my form to 3 fields for show here, but it works fine only if I remove all selects from form. I think bug related with form fields, but I dont't know why removing exif helps.
length of $item['exif'] is not so big, attached output of var_dump
[exif_var_dump.txt](https://github.com/awcodes/filament-curator/files/12224632/exif_var_dump.txt)

**Comment by howdu** [comment]
Agree that's not very big it's probably the exif is just tipping it over the limit. 

Try increasing your php.ini settings specifically `post_max_size`

```
session.gc_maxlifetime 10800
max_input_time         10800
max_execution_time     10800
upload_max_filesize    110M
post_max_size          120M
```

**Comment by awcodes** [comment]
Can you attach the images in a zip by any chance so I can do some testing with the raw files. I would use the ones you provided but want to make sure those weren't modified by GitHub.

**Comment by pinkertoon** [comment]
> Agree that's not very big it's probably the exif is just tipping it over the limit.
> 
> Try increasing your php.ini settings specifically `post_max_size`
> 
> ```
> session.gc_maxlifetime 10800
> max_input_time         10800
> max_execution_time     10800
> upload_max_filesize    110M
> post_max_size          120M
> ```

Changed post_max_size to 500M and other settings like in your example. Nothing changed :(

**Comment by pinkertoon** [comment]
> Can you attach the images in a zip by any chance so I can do some testing with the raw files. I would use the ones you provided but want to make sure those weren't modified by GitHub.

Archive attached
[images.zip](https://github.com/awcodes/filament-curator/files/12246747/images.zip)

**Comment by awcodes** [comment]
Sorry, I can't replicate this either. My advice is to remove each of your other fields one by one to see if one of the selects in particular is causing the issue.

I'm going to close this for now. Feel free to reopen if you can provide a reproduction repo with seeders or can isolate the issue specifically with the Curator plugin.
