### ISSUE TITLE
copy url not working

### ISSUE THREAD

**Issue by valetto** [awcodes/filament-curator#257]
getting js error on console while try to hit copy url
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText
<img width="950" alt="Screenshot 2023-08-06 at 4 44 07 PM" src="https://github.com/awcodes/filament-curator/assets/6079699/973ff6ca-c131-492b-b890-cb199052b946">

**Comment by awcodes** [comment]
What browser are you using?

**Comment by valetto** [comment]
chrome Version 115.0.5790.114

**Comment by awcodes** [comment]
Sorry, i can't replicate this. Maybe a setting or extension in your browser is disabling the clipboard on the navigator object.

**Comment by rahmat-dev** [comment]
**As with many new APIs, the Clipboard API is only supported for pages served over HTTPS.**
source: https://web.dev/articles/async-clipboard

@valetto if you're using valet or herd, try to set secure feature to enabled and access from https.
