### ISSUE TITLE
Curator for V2 - edit image on aws fails

### ISSUE THREAD

**Issue by phpsa** [awcodes/filament-curator#269]
Uploading new media items works as expected,

But - go edit an existing media item and upload to replace it and it breaks, deletes the old image and does not insert the new image,

some debugging and notice on the mediaObserver during the updating process it is passing the old media only and not the newly updated media item

**Comment by phpsa** [comment]
Further Debugging:
DB Record before update:
`path=media/80836ea4-93c9-42cf-a886-1d53cd991b52.jpg`

During the save process of an updated image:
File: Uploader.php line 92 state (result of saveUploadedFiles() method)
`"path" => "media/055da024-6e0e-471f-b10a-5ed40c2c1cb8.webp"`

in observer of same call:

$media->getOriginal = `"path" => "media/80836ea4-93c9-42cf-a886-1d53cd991b52.jpg"`
$media->getDirty = `"path" => "media/055da024-6e0e-471f-b10a-5ed40c2c1cb8.webp"`

$media at end of updating method of observer:
`"path" => "media/80836ea4-93c9-42cf-a886-1d53cd991b52.webp"`

DB Record after update:
`path=media/80836ea4-93c9-42cf-a886-1d53cd991b52.jpg`


Boiled it down to the storage->move command in the observer. - when acl's are not enabled on S3

**Comment by awcodes** [comment]
If the issue is with Storage->move(), wouldn't that be an issue in the Flysystem adapter?

**Comment by phpsa** [comment]
Was originally thinking on their end, however, believe their code works as expected, however thinking that perhaps this plugin should get the result of storage->move() and if false, copy it over instead?

move tries to read acl's where as if you do a storage::put from storage::get  as a fallback option then delete it may work better,

I understand that this may not fall within your area's of wanting to maintain, so an alternative may be to allow a switch to disable the uploading of a new media item in the media edit screen, or even better perhaps the ability to enable or disable keeping original upload name when replacing media, this could default to true and if false, would simply not rename the file during upload.

thanks for the plugin though, it is a livesaver.

**Comment by awcodes** [comment]
I'm not opposed to it. If it makes things better then I'm for it. Problem I have at the moment is that I don't have a way to test Aws integrations. 

What stands out the most in your findings is that the db isn't reflecting the updated ext. which is weird because with a non aws disk it persists correctly.

**Comment by awcodes** [comment]
Can you also help me to understand the application/use case of a bucket that doesn't use acl's. I was under the impression that they all needed them even if it was public.

**Comment by phpsa** [comment]
There are use cases where for higher security - the bucket is restricted to only the specific user and all objects are created owned by only that user., this is due to a terraform setup and hosting restrictions place on the system,

I would be happy to update the code in the correct manner and test for you should it be needed.. (

BTW: agree with keeping acls, however in this specific use case, I do not have the ability to override the provider setup.

which pattern would you prefer?

**Comment by awcodes** [comment]
I’m ok with you submitting a Pr to the observer to handle this specific use case. In v3 the observer is registered in a way that can be hot swapped via a service provider. So I’m less worried about it for V3.

**Comment by awcodes** [comment]
Closing as this is stale.
