### ISSUE TITLE
Division by zero when using `.svg` files

### ISSUE THREAD

**Issue by leo-unglaub** [awcodes/filament-curator#275]
Hey,
i just noticed an exception in your extension. If an `.svg` file is used then the code does not know the size and fails with a `division by zero`. The following line in `vendor/awcodes/filament-curator/src/View/Components/Glider.php:118 ` is the problem:

```php
$height = floor($width * ($this->media->height / $this->media->width));
```

As you can see, if `$this->media->with` is unknown, it fails.

Thanks and greetings

**Comment by awcodes** [comment]
Thanks. Will dig into it this weekend.

**Comment by awcodes** [comment]
I'm thinking this should throw an exception since you are trying to use an svg image with srcsets.

**Comment by leo-unglaub** [comment]
But `svg` is a valid format in srcset.

**Comment by awcodes** [comment]
It doesn't make sense to use srcset with svg. Srcset loads different physically sized images. Svg isn't saved at different sizes, there is no need since it is vector based. So you'd load one svg and control its size with css.
