### ISSUE TITLE
Bug with filament-tiptap-editor

### ISSUE THREAD

**Issue by vovacorgo** [awcodes/filament-curator#281]
Getting an error when use curator as editor for filament tiptap-editor
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/eca4703b-036b-4ad3-b139-8fb51a25d279)
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/0e7658b2-b024-4f7f-a4bc-65b0e2da5dbf)
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/18fbf1f6-5399-4e43-abe7-cad7fdeb8aea)
i config file:
```
//    'media_action' => FilamentTiptapEditor\Actions\MediaAction::class,
    'media_action' => Awcodes\Curator\Actions\MediaAction::class,
    'link_action' => FilamentTiptapEditor\Actions\LinkAction::class,
```

**Comment by vovacorgo** [comment]
Filament version:^3.0 titapeditor:3.0@beta, curator:v3.0.0-beta.9

**Comment by awcodes** [comment]
This is known. Both plugins are still in progress waiting on some livewire bugs too.

But I will get this addressed soon.
