### ISSUE TITLE
Tip-Tap editor media-picker cant insert image 

### ISSUE THREAD

**Issue by vovacorgo** [awcodes/filament-curator#283]
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/92557441-5059-400f-a411-2c7f964598b8)
When i try to insert image button insert doesnt apear
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/f2b630be-4978-4afb-8cfe-ebe55dad3d6c)
I have errors in console but doesnt really that they connected with the problem:
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/ec387044-02a8-40e9-a805-93a76552d8a0)

**Comment by vovacorgo** [comment]
Also when trying to load new image to the server  from picker : get an error:
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/18abbb25-f41d-46e6-bc01-0914c2069ef7)
That error appers not only in tip tap editor but also in usual filament field:
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/258610d7-2c55-417e-8e60-1bef4584bbe5)
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/2a3a255e-1d91-478c-82f5-377f2bc1cf3e)

Thats mean plugin not properly works

**Comment by awcodes** [comment]
Make sure you're on the latest version of the plugin as well as Filament and Livewire. Everything is working correctly for me.

**Comment by vovacorgo** [comment]
> Make sure you're on the latest version of the plugin as well as Filament and Livewire. Everything is working correctly for me.

i have changed version filament to 2, also downgrade version of curator. Questin can i integrate Other WYSIWYG with your plugin?

**Comment by awcodes** [comment]
Only if they provide an adapter to use it. I don't have any control over their plugins.
