### ISSUE TITLE
[V2] Cant set string field name 

### ISSUE THREAD

**Issue by vovacorgo** [awcodes/filament-curator#287]
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/942d2450-8554-4bd0-8890-87eef2cbbe30)

With that code : ` CuratorPicker::make('image')`
on filament 2 and curator 2 throws an error, if set integer works fine

**Comment by vovacorgo** [comment]
#288  Maybe that should help

**Comment by awcodes** [comment]
UUID an ULID support was added in v3. Currently, I do not have plans to back port it into v2 as it requires changes to a lot of other places too and could potentially break v2.
