### ISSUE TITLE
 [v2]    Error while building assets

### ISSUE THREAD

**Issue by vovacorgo** [awcodes/filament-curator#291]
Cant build with ( npm run build) `@import '../../node_modules/cropperjs/dist/cropper.css';`  in plugin.css 
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/5aa88799-ca41-49cb-89b7-ebe069d9814e)

But buids with : `@import '../../../../../node_modules/cropperjs/dist/cropper.css';` :
![изображение](https://github.com/awcodes/filament-curator/assets/47760619/79f56064-0ea3-4ba2-ba66-ec8ce5ebfc92)

**Comment by vovacorgo** [comment]
#292

**Comment by awcodes** [comment]
Yea I'm still not sure what I want to do with the css yet. I'm not a fan of how filament v3 is handling it. I will it get figured out soon. 

For now though you can drop the import for croppers css file. And import the dist/curator.css, I believe.

**Comment by vovacorgo** [comment]
> Yea I'm still not sure what I want to do with the css yet. I'm not a fan of how filament v3 is handling it. I will it get figured out soon.
> 
> For now though you can drop the import for croppers css file. And import the dist/curator.css, I believe.
i cant do that because after reinstall lib i will have same problem with building - i cant do that variant because that project will be in production. Can you give me some recomendation to ignore that error. Maybe it posible intercept that import in the Laravel project?
