### ISSUE TITLE
Error composer install with filament v3

### ISSUE THREAD

**Issue by stefantheo** [awcodes/filament-curator#295]
Problem 1
    - Root composer.json requires awcodes/filament-curator ^2.10 -> satisfiable by awcodes/filament-curator[v2.10.0].
    - awcodes/filament-curator v2.10.0 requires filament/filament ^2.0 -> found filament/filament[v2.5.3, ..., v2.17.53] but it conflicts with your root composer.json require (3.0).

**Comment by awcodes** [comment]
`composer require awcodes/filament-curator:"^3.0"`

Sorry, just updated the readme on the 3.x branch.

**Comment by aeq-dev** [comment]
I'm trying to install it but I got this error : 
```
Problem 1
    - Root composer.json requires awcodes/filament-curator ^3.0, found awcodes/filament-curator[v3.0.0-alpha1, ..., 3.x-dev] but it does not match your minimum-stability.
```

**Comment by awcodes** [comment]
I answered you in the discord. :)
