### ISSUE TITLE
Curations V2 - Image source not readable when using S3 disk

### ISSUE THREAD

**Issue by richdynamix** [awcodes/filament-curator#314]
### Filament Version

v2.17.52

### Plugin Version

v2.10.1

### PHP Version

PHP 8.2

### Problem description

When the Curator plugin has been configured with a custom GlideServer to utilise S3 as the main source disk as well as the cache disk the creation of Curations fails due to a "Image source not readable" exception being thrown by Intervention.

When drilling down to the cause in `vendor/awcodes/filament-curator/src/Components/Modals/CuratorCuration.php:23` the `Image::make()` method fails to read the source file for curations. This seems to be related to the Storage facade using the path method for the correct disk. However, as per the Laravel docs, the path method will return the relative path to the S3 bucket when using a S3 disk. This causes the Image::make method to fail.

To test the theory, I swapped the path method for the url method and it worked as expected. I am not sure of the performance hit or the reproductions from this action for other setups but it might be a sensible work around for this problem. 

### Expected behavior

When creating a curation, when the user configures their new curation and clicks the Save Curation button at the bottom of the configuration panel, they should be taken to the main media page with the new curation in place.

### Steps to reproduce

Set env - `FILESYSTEM_DISK=s3`

Ensure the S3 disk has the visibility configuration in Filesystems.php -  `'visibility' => 'public',`

Create a custom glide server in the AppServiceProvider.php - 

```php
        $glideServer = ServerFactory::create([
            'driver' => 'gd',
            'response' => new LaravelResponseFactory(app('request')),
            'source' => Storage::disk('s3')->getDriver(),
            'cache' => Storage::disk('s3')->getDriver(),
            'cache_path_prefix' => '.cache',
            'max_image_size' => 2000 * 2000,
        ]);

        Curator::resourceLabel('media')
            ->disk('s3')
            ->cloudDisks(['s3'])
            ->glideServer($glideServer);
```

**Comment by awcodes** [comment]
I don't really have a way to test this. But see if v2.10.2 resolves the issue for you.
