### ISSUE TITLE
CurationPreset depend on screen size 

### ISSUE THREAD

**Issue by lacehate** [awcodes/filament-curator#317]
### Filament Version

v2.0

### Plugin Version

v2.2

### PHP Version

PHP 8.0.2

### Problem description

CurationPreset depend on screen size, if preset width or height is bigger than window size, choosing preset sets width and height closest values to the preset, i attached code and screenshots, 
I hope I was able to convey my thought to you, please ask questions  
/:
```
 Curator::navigationGroup('Контент')
            ->navigationSort(2)
            ->resourceLabel('Файловый менеджер')
            ->pluralResourceLabel('Файловый менеджер')
            ->mediaModel(Media::class)
            ->acceptedFileTypes(['image/*'])
            ->disableResourceRegistration();

        $this->app->bind(MediaResource::class, fn() => new CustomMediaResource());
        $this->app->bind(MediaResource\EditMedia::class, fn() => new CustomEditMedia());
        $this->app->bind(MediaResource\CreateMedia::class, fn() => new CustomCreateMedia());
        $this->app->bind(MediaResource\ListMedia::class, fn() => new CustomListMedia());

        Curator::curationPresets([
            CurationPreset::make('lead_img')
                ->label('lead img')
                ->width(1550)
                ->height(707),
            CurationPreset::make('lead_img_mobile')
                ->label('lead img mobile')
                ->width(351)
                ->height(480),
        ]);
```

![Screenshot 2023-10-04 at 15 35 14](https://github.com/awcodes/filament-curator/assets/97598328/09962554-d027-4f24-ba14-7841ecbd7647)
![Screenshot 2023-10-04 at 15 39 56](https://github.com/awcodes/filament-curator/assets/97598328/fbd7e44a-2c40-4f1a-92d0-2acf7f0f5fd6)
![Screenshot 2023-10-04 at 15 40 24](https://github.com/awcodes/filament-curator/assets/97598328/4f2e9d60-90ba-4bbd-b577-a2a397205d60)

### Expected behavior

i expect it to correctly display image and crop it using presets

### Steps to reproduce

create CurationPreset, set width and height of preset bigger than your crop window, where u select created presets, download high resolution image and try to crop it using ur preset

**Comment by awcodes** [comment]
I'll do some digging and get back to you. This could even be a bug in cropper.js, but can't say for sure at the moment.

**Comment by lacehate** [comment]
> I'll do some digging and get back to you. This could even be a bug in cropper.js, but can't say for sure at the moment.

Thank you for your answer!

**Comment by awcodes** [comment]
Ok. I'm not seeing anything on the Curator side that would keep this from working like you want it to.

I am seeing a lot of mention through out cropperjs docs talking about things being bound to the container size itself which leads me to believe that this is a either a bug in cropperjs or an unimplemented feature.

So, I do not have a way to fix this at this time. I am more than open to PRs if you can find a fix for it. Sorry.
