### ISSUE TITLE
Media Modal Style Issue and Curator.css Not Loading Successfully

### ISSUE THREAD

**Issue by mohaphez** [awcodes/filament-curator#318]
### Filament Version

v3.0

### Plugin Version

v3.0.5

### PHP Version

PHP 8.1

### Problem description

I encountered an issue with the select media modal in your repository. It seems that the Curator.css file is not loading correctly, resulting in incorrect styling for the media modal.

![Screenshot_2023-10-04_18-39-31](https://github.com/awcodes/filament-curator/assets/20874565/00d4ffcd-f1bc-4a47-ae15-ddcf7113d3e5)

Upon investigation, I found that removing the loadedOnRequest() from the following code resolves the issue:

FilamentAsset::register([
    AlpineComponent::make('curation', __DIR__ . '/../resources/dist/curation.js'),
    Css::make('curator', __DIR__ . '/../resources/dist/curator.css')->loadedOnRequest(),
], 'awcodes/curator');

After making this change, everything works as expected.

### Expected behavior

The select media modal should have the correct styling, and the Curator.css file should load successfully.

![Screenshot_2023-10-04_18-40-32](https://github.com/awcodes/filament-curator/assets/20874565/4bb4c865-3330-4e18-af53-d98080dcbbff)

### Steps to reproduce

Visit the page with the media modal.
Observe the incorrect styling and the Curator.css not loading.

**Comment by awcodes** [comment]
This works correctly.

Try running `composer filament:assets`

**Comment by mohaphez** [comment]
Thank you for your prompt response.

I appreciate your suggestion, and I did run 
`sail php artisan filament:assets`, 
`sail php artisan cache:clear`, 
`sail php artisan optimize:clear`, 

which resulted in "Successfully published assets!",  including the curator.css file in the 'public/awcodes/curator' path.

Unfortunately, the issue persists, and the styles are not applied correctly. As a temporary solution, I have registered the assets manually in the service provider boot method:

```php
FilamentAsset::register([
    Css::make('/awcodes/curator', './vendor/awcodes/filament-curator/resources/dist/curator.css'),
]);
```

While this workaround allows me to proceed, I believe there might be an underlying issue with the `sail php artisan filament:assets` command not addressing the problem.

I would appreciate further assistance in identifying and resolving the root cause of this issue. If you need any additional information or if there are specific logs or commands you'd like me to run, please let me know.

Thank you for your support.

**Comment by awcodes** [comment]
hmm. if it's an issue with sail, then there's not much I can do, nor can I replicate the issue.

The styles are loaded on demand when the picker field is on the page using filament's asset system so they are only loaded when needed.

If you can provide me with a reproducible repo I'm happy to pull it down and see if I can replicate with your code base.

**Comment by mohaphez** [comment]
Hi Adam,

Thank you for your quick response and guidance.

To provide more context, I've created a new project from scratch and installed everything, but I'm encountering the same result.

I've made the project repository available on GitHub: [awcodes-curator](https://github.com/mohaphez/awcodes-curator). Feel free to pull it down and test it on your end. If you need any additional information or if there's anything else I can do to assist in resolving this issue, please let me know.

Thanks again for your support.

**Comment by awcodes** [comment]
You don't have a custom theme setup in that repo.

The 3rd step in the README even walks you through it.
