### ISSUE TITLE
CuratorPicker can't be placed within a Group within a Grid anymore

### ISSUE THREAD

**Issue by Voltra** [awcodes/filament-curator#355]
### Filament Version

3.0.102

### Plugin Version

3.1.4

### PHP Version

8.1.0

### Problem description

In one of my block's schema for filament-fabricator, I had put the picker within group that was within a grid (for layout and customization purposes). It used to work just fine, but after updating my dependencies yesterday it now causes an infinite loop

### Expected behavior

It should work fine, as it used to

### Steps to reproduce

Rewrite a component of an existing app with existing data, and place the `CuratorPicker` inside a `Group` and put that `Group` into a `Section`.

Might have to put all that within a `Block` as that's what filament-fabricator uses

**Comment by Voltra** [comment]
After another test, I can confirm the issue only happens when there's a value for that field. When the field is empty and we pick an image it works fine, but refreshing the page after saving triggers the issue

**Comment by awcodes** [comment]
Sorry. I can't replicate the issue, and can't speak for anything that might be related to issues with the Fabricator plugin. If you can provided a reproduction repo, I can look into it more.

```php
Forms\Components\Section::make('Section')
    ->schema([
        Forms\Components\Group::make([
            CuratorPicker::make('featured_image_id')
                ->relationship('featured_image', 'id'),
        ])
    ]),
```

![Screenshot 2023-11-27 at 10 49 43 AM](https://github.com/awcodes/filament-curator/assets/3596800/8283814d-a474-4aa5-beb2-6cc5360a7f0d)

**Comment by Voltra** [comment]
I have indeed tried myself to make reproduction repo, but failed for now. It's probably a third-party compatibility issue, or an issue on another dependency completely. I'll close this issue for now
