### ISSUE TITLE
Glide Signature Fails to Validate

### ISSUE THREAD

**Issue by richdynamix** [awcodes/filament-curator#360]
### Filament Version

v3.1.4

### Plugin Version

3.1.5

### PHP Version

8.2.13

### Problem description

Image urls rendered on the website using the `<x-curator-glider>` tag results in 403 due to failing signature validation on the media controller.

For context, I have a custom GlideServer setup on our site with the following - 

```php
class CustomServerFactory implements Contract
{
    public function getFactory(): ServerFactory | Server
    {
        return ServerFactory::create([
            'driver' => 'gd',
            'response' => new LaravelResponseFactory(app('request')),
            'source' => Storage::disk('s3')->getDriver(),
            'cache' => Storage::disk('s3')->getDriver(),
            'cache_path_prefix' => '.cache',
            'max_image_size' => 2000 * 2000,
        ]);
    }
}
```

This is working as expected. Files are uploaded into the S3 bucket and I can render them on the frontend with the curator-glider tag. Additionally, there is a `.cache` folder on the S3 bucket.

The problem is when I am trying to utilise the Curator functionality with Glide by using the attributes on the tag. Trying to resize the image with width does not work, results in a width attribute being applied to the img tag but the source image is still the large image.

I have tried srcset with sizes, and while the html rendered is correct, the resulting source urls are all the same, so when inspecting the computed properties for the `currentSrc` the source is the main full size image, at all breakpoints.

On inspection of all other attributes, none of these work, resulting in an img tag with no altered URL for manipulation, even when trying to set the format to webp.

My next attempt to have resizable images was to use the `glide` attribute and pass in the glide query string. This is where the page renders broken images. On inspection of the image URL, it is resulting in a 403. I investigated the MediaController and noticed the signature validation is failing. The validation is expecting a `$param['s']` to be passed in but the request does not have this when I dumped the request object in the controller. 

When I commented out the signatire validation, the urls were generated correctly resulting in the images with manipulations as expected. It seems the curator-glider tag is not working correctly with a custom glide server factory.

### Expected behavior

When viewing a page with the <x-curator-glider> tag being used with attributes setting manipulations we expect the rendered image to match the passed in manipulations.

Additionally, setting the glide string manually should render the images with manipulations as expected.

### Steps to reproduce

Create a custom server factory utlising S3 as the source and cache storage.

```php
class CustomServerFactory implements Contract
{
    public function getFactory(): ServerFactory | Server
    {
        return ServerFactory::create([
            'driver' => 'gd',
            'response' => new LaravelResponseFactory(app('request')),
            'source' => Storage::disk('s3')->getDriver(),
            'cache' => Storage::disk('s3')->getDriver(),
            'cache_path_prefix' => '.cache',
            'max_image_size' => 2000 * 2000,
        ]);
    }
}
```

In filesystems.php config, set a custom AWS URL on the S3 driver to utilise a CDN url.

Upload an image to the media resource and confirm the image exists on the bucket and is viewable in the frontend using the 

```html
      <x-curator-glider
          class="h-48 w-full object-cover"
          media="{{ $model->featured_image }}"
      />
```

Alter the tag to make some manipulations - 

### Using glide query string
```html
      <x-curator-glider
          class="h-48 w-full object-cover"
          media="{{ $model->featured_image }}"
          glide="w=500&q=80&f=webp"
      />
```

`Results in a 403`

### Using tag attributes
```html
      <x-curator-glider
          class="h-48 w-full object-cover"
          media="{{ $model->featured_image }}"
          width="500"
          format="webp"
          quality="80"
          height="auto"
      />
```

`Results in no change to the URL and no manipulation being applied`

**Comment by awcodes** [comment]
Can you check the `getSignedUrl()` method in `Awcodes\Curator\Models\Media`? I'm thinking for some reason your media item it's passing the conditional check.

**Comment by richdynamix** [comment]
Ah found the culprit - 

```php
        if (
            !$this->resizable ||
            in_array($this->disk, config('curator.cloud_disks')) ||
            !Storage::disk($this->disk)->exists($this->path)
        ) {
            return $this->url;
        }
```

My default disk is S3, which exists in the cloud disk array, so this condition returns true, which always results in the source url being returned. I removed S3 from the cloud disk config to resolve.

Thank you.

**Comment by awcodes** [comment]
I wouldn't recommend removing the 's3' from the cloud_disks config.

I've added a 'force' attribute in the latest version that allows you to bypass the check on the model.
