### ISSUE TITLE
The curator picker modal does not work in the latest version.

### ISSUE THREAD

**Issue by nakir00** [awcodes/filament-curator#364]
### Filament Version

v3.0-stable

### Plugin Version

v3.1

### PHP Version

PHP 8.1

### Problem description

The curator selector modal does not work in the latest version. The button to add on the form just loads and then stops.The modal window does not open. my code was working before i updated the package so i just downgraded to v3.0.6 and the picker work in that version

### Expected behavior

I expect the modal picker to open.

### Steps to reproduce

i just had to update to v3.1

win : 11

php : ^8.1

filament : 3.0-stable

filament-curator : v3.1

**Comment by ufukseyithan** [comment]
My modal works normally. However, inside a page where I don't use the default filament layout it won't open. I think I need to include some HTML or script inside my head and body tags in the layout but don't know what exactly.

**Comment by awcodes** [comment]
Try with v3.2.0.

You will need to add `<x-curator::modals.modal />` to your layout before the closing body tag.

**Comment by ufukseyithan** [comment]
Do I have to add that with v3.2? Because it can't find the component at the moment. I am using v3.1.

I tried: `<x-curator::modals.modal />` and `<x-filament::curator::modals.modal />`, none worked. Any ideas? Thanks

**Comment by awcodes** [comment]
Yes. It is specific to v3.2
