### ISSUE TITLE
registerRenderHook does not check if Panel actually loads Curator Plugin

### ISSUE THREAD

**Issue by salohcin714** [awcodes/filament-curator#368]
### Filament Version

v3.1.10

### Plugin Version

v3.2.0

### PHP Version

PHP 8.2

### Problem description

We are running a multi-tenant, multi-database backend. The main backend for us does not use Curator as there is no need for media. The tenant admin panel allows tenants to upload photos, so we do use Curator for them.

Because of this, our main database does not contain a media table.

### Expected behavior

The hook needs to check to make sure the Curator plugin is actually loaded before firing the hook.

### Steps to reproduce

Try to load a page that uses Filament that does not load the Curator plugin while using a database that doesn't have the media table.

**Comment by awcodes** [comment]
hmm. ok. I don't have a way to test this particular setup. Can you try updating the ServiceProvider in the vendor directory to make sure the plugin check works for the usecase and let me know. Or, would be really appreciated if you could submit it as a PR.

Thanks.
