### ISSUE TITLE
Curator picker field not working anymore after update

### ISSUE THREAD

**Issue by DanielSpravtsev** [awcodes/filament-curator#372]
### Filament Version

3.1.13

### Plugin Version

3.2.2

### PHP Version

8.2

### Problem description

After updating from v3.1.1 because of bug described in https://github.com/awcodes/filament-tiptap-editor/issues/236 to last version, curator picker no more working.

It open modal with media, but when you try to insert it nothing happens and following error outputs to console
```
file-upload.js?v=3.1.14.0:40 Uncaught (in promise) Could not find Livewire component in DOM tree
(anonymous) @ file-upload.js?v=3.1.14.0:40
```

### Expected behavior

Insert media to field

### Steps to reproduce

1. Select media
2. Verify that it wasn't added

**Comment by awcodes** [comment]
Are you using panels or standalone forms package?

**Comment by DanielSpravtsev** [comment]
> Are you using panels or standalone forms package?

Panels

**Comment by awcodes** [comment]
Make sure you have the `CuratorPlugin::make()` registered in your panel provider. Seems to be working fine for me on latest Filament and Plugin versions.

Possibly view cache, and also make sure you rebuild your assets with `npm run build`

https://github.com/awcodes/filament-curator/assets/3596800/a036b2f2-2fce-47a5-8872-4513ca57de35

**Comment by DanielSpravtsev** [comment]
> Make sure you have the `CuratorPlugin::make()` registered in your panel provider. Seems to be working fine for me on latest Filament and Plugin versions.
> 
> Possibly view cache, and also make sure you rebuild your assets with `npm run build`
> 
>  Screen.Recording.2023-12-08.at.8.51.44.AM.mov

Tested it, plugin registered, composer updated, view cache cleared, assets rebuilded, browser cache cleated, same issue on select

https://github.com/awcodes/filament-curator/assets/31937522/579afef2-be15-41b4-b224-1f7e9fc9d715

**Comment by awcodes** [comment]
Sorry, not sure what to tell you. If you can provide a reproduction repo I can investigate further. But I just can't replicate what I'm seeing in your video.

**Comment by DanielSpravtsev** [comment]
> Sorry, not sure what to tell you. If you can provide a reproduction repo I can investigate further. But I just can't replicate what I'm seeing in your video.

I'll create a reproduction repo as soon as possible

**Comment by DanielSpravtsev** [comment]
@awcodes If it makes sense for you, there are new error in console on the last version 
`Livewire Entangle Error: Livewire property ['data.files_to_add'] cannot be found on component: ['curator-panel']`

Will try to create reproduction repo today

**Comment by DanielSpravtsev** [comment]
> @awcodes If it makes sense for you, there are new error in console on the last version `Livewire Entangle Error: Livewire property ['data.files_to_add'] cannot be found on component: ['curator-panel']`

Following problem appears on https://github.com/awcodes/curator-demo repo with the last Filament update (3.1.20)

**Comment by awcodes** [comment]
Livewire property console error will be fixed in the next release.

Are you still having your original issue? If not, can you close the issue please.

**Comment by fvanzeijl** [comment]
Hey, error still exists on 3.3.0.
If I try to add image via the curator-picker, I get the error. I can add it, but the overflow-hidden on html-root still persist and I can not scroll down to save-button (in filament-resource).

<img width="546" alt="curator-error" src="https://github.com/awcodes/filament-curator/assets/100679001/636272a8-791d-4989-97ee-b11daa142a6b">

I found out the error is thrown by call "setMediaForm"-method in CuratorPanel::addToSelection (line 250). I dont know, what the method exactly does, but if I comment out the call, no errors will be thrown and the picker/panel works.

**Comment by awcodes** [comment]
This error is in core. It has something to do with Livewire loosing track of alpine components when modals/forms get hidden. I think there is a PR about it on the Livewire repo.

I also can not replicate your scrolling issue. Page is scrolling fine for me after closing the panel.

**Comment by DanielSpravtsev** [comment]
@awcodes Coming back to this issue after a long time and was able to fix it after deleting published vendor resources 🤣 
Thats crazy! Hope this help somebody
