### ISSUE TITLE
Filament Curator Srcset Not Changing Image Sizes

### ISSUE THREAD

**Issue by Nathan269** [awcodes/filament-curator#380]
### Filament Version

3.1.20

### Plugin Version

3.2.4

### PHP Version

8.2

### Problem description

No matter what my screen size is set to, whether it's a small screen, medium, large, etc. The image size doesn't adjust accordingly even when I have srcset & sizes set. The set size of the image when you look at the current src within the properties always seems to be set to the largest size set.

### Expected behavior

Images should adjust in size depending on what screen size you have when viewing the page.

### Steps to reproduce

1. Upload an image using Filament Curator
2. Use the following code (adjust your media id to what your image id is set to):

`
       <div class="aspect-video w-64">
            <x-curator-glider
                class="object-cover w-auto"
                :media="10"
                :srcset="['1024w', '640w']"
                sizes="(max-width: 1200px) 100vw, 1024px"
                format="webp"
                quality="80"
                force="true"
                alt=""
            />
        </div>
`

**Comment by awcodes** [comment]
Srcset appears to be working fine to me. Even with your example.

https://github.com/awcodes/filament-curator/assets/3596800/326c8594-17e2-4430-bcf1-cba3bd4de7cf
