### ISSUE TITLE
shouldRegisterNavigation Closure type missing

### ISSUE THREAD

**Issue by WilliamPinto-Olmos** [awcodes/filament-curator#381]
### Filament Version

v2.17.55

### Plugin Version

v2.10.2

### PHP Version

PHP 8.2

### Problem description

the `registerNavigation()` method in Curator.php Facade is expected to receive a `bool|Closure|null` types, but the actual variable `$shoudlRegisterNavigation` is typed only as `bool`.

```php
public function registerNavigation(bool|Closure|null $condition = true): static
{
    $this->shouldRegisterNavigation = $condition;

    return $this;
}
```

This ends up in an error when passing a closure to the `registerNavigation()` in the Curator facade, as I need to determine the registerNavigation using the authenticated user, that's why I needed to be evaluated in the closure.

### Expected behavior

You should be able to pass a Closure to the `registerNavigation()` to determine whether register the navigation. 

### Steps to reproduce

In any service provider using the Curator facade, use the method `registerNavigation()` passing a Closure as a parameter.

```php
Curator::registerNavigation(static fn () => auth()->user()->hasRole('some-role'));
```

You will see the following error.

![image](https://github.com/awcodes/filament-curator/assets/60890527/a8cc55ea-8299-495b-a3f2-96ed18c5e269)

This is caused by the property $shouldRegisterNavigation being declared only as bool type.

```php
protected bool $shouldRegisterNavigation = true;
```

If you change the vendor and type it as bool|Closure it works fine as the `shouldRegisterNavigation()` method evaluates the variable using `evaluate()` function.

**Comment by awcodes** [comment]
Fixed in v2.10.3
