### ISSUE TITLE
The CuratorPicker modal dose'nt open in modular structure

### ISSUE THREAD

**Issue by vahidForughi** [awcodes/filament-curator#406]
### Filament Version

v3.1.0

### Plugin Version

v3.4.2

### PHP Version

PHP 8.1.10

### Problem description

I used nwidart/laravel-modules , and integrate that with filament by some changes in AdminServiceProvider manually .
Everything is fine as long as I use CuratorPicker in the Resources in App namespace  , But When I add CuratorPicker to Modules Resources ,  The CuratorPicker modal does not open. 

Note: The curator media action in Tiptap works fine.

### Expected behavior

The curator media action in Tiptap works fine, So CuratorPicker should works too.

### Steps to reproduce

Whenever add CuratorPicker to Modules Resources, modal dose'nt open.

**Comment by awcodes** [comment]
Will definitely need a reproduction repo for this. I don't use that modules package.

**Comment by vahidForughi** [comment]
I found the problem. It had nothing to do with modularity and relocation.
Using the same section name as CuratorPicker field name creates the problem and changing the section name solved it !!

```
public static function form(Form $form): Form
{
    return $form
        ->schema([
            // ...
            Section::make('Thumbnail')
                ->schema([
                    CuratorPicker::make('thumbnail')
                ])
        ])
}
```
