### ISSUE TITLE
defaultImageUrl doesn't work with CuratorColumn

### ISSUE THREAD

**Issue by ArtMin96** [awcodes/filament-curator#417]
### Filament Version

v3.1.42

### Plugin Version

v3.4.4

### PHP Version

PHP 8.0.30

### Problem description

`defaultImageUrl` doesn't work for `CuratorColumn` but works for `ImageColumn`.

### Expected behavior

That it should work

### Steps to reproduce

Just use `defaultImageUrl`

**Comment by awcodes** [comment]
Use the native Image column instead. CuratorColumn will be deprecated in the next version.

**Comment by ArtMin96** [comment]
Should I close this issue?

**Comment by awcodes** [comment]
Leave it for now. Thank you. I'll take care of it. Thanks.
