### ISSUE TITLE
Str ->Contains in Blade files

### ISSUE THREAD

**Issue by atellier2** [awcodes/filament-curator#45]
I had a bug with ``str`` helper in Laravel 9. I replace with https://laravel.com/docs/9.x/helpers#method-str-contains and it's OK

before
```php
@if (Str($currentItem['type'])->contains('image'))
```

After
```php
@if (Str::contains($currentItem['type'],'image'))
```

Files concerned : See https://github.com/awcodes/filament-curator/search?q=contains

**Comment by awcodes** [comment]
What exactly is the bug. The str() helper is just a wrapper around the Str facade. Those are virtually identical and I haven't had any issues with it on Laravel 9.
