### ISSUE TITLE
Can't add a video mp4 file with the curator picker

### ISSUE THREAD

**Issue by Cayaf89** [awcodes/filament-curator#484]
### Filament Version

v3.2.79

### Plugin Version

v3.5.7

### PHP Version

8.2.17

### Problem description

When I try to add a video file (.mp4), I get an error : Undefined array key "file"

![image](https://github.com/awcodes/filament-curator/assets/25308716/d72bcf8b-12b8-4604-815c-66191a628f4b)

### Expected behavior

Have a validation error for the file max_size config instead of the php error.

### Steps to reproduce

1. Create a resource with a form field CuratorPicker
2. Open Curator modal
3. Add the video file (with size larger than max_size config)
4. Click on insert

### Relevant log output

```shell
https://flareapp.io/share/bP9gpDo5#context-request-body
```

**Comment by Cayaf89** [comment]
I found out where my problem was : it was the max_size config that were set to 5000 but i tried to upload a video that is 6Mo

It would be great to have a validation message if the file larger than the max_size instead of this error.

**Comment by awcodes** [comment]
I'll see what I can find, but the error doesn't match the resolution. I would expect, in this case, a 500 thrown by livewire and not by a filament class. Not sure this is truly related to the plugin itself. Thank you for the feedback back.

**Comment by xalabama** [comment]
I have tested this setup also and can't confirm that the described behavior happens on upload a file that is bigger than max_size from config. I got a normal validation error message from livewire inside the form. Maybe it helps to share more details about your implementation.
