### ISSUE TITLE
Media Resource List Page

### ISSUE THREAD

**Issue by onairmarc** [awcodes/filament-curator#487]
### Filament Version

v3.2.81

### Plugin Version

v3.5.8

### PHP Version

8.3

### Problem description

When viewing Media Resource List page, the images are not aligned with the check box container and are not clickable from the image nor the checkbox. I doubled checked my theme files just to make sure I didn't do anything incorrectly and it appears that everything is in working order there.

In a last ditch attempt, I revered to v3.5.7 to see if that resolved the issue and it did. I'm not sure what changed in v3.5.8, but it appears to be a breaking change regarding displays and interactions.

### Expected behavior

The image should be clickable from the resource list page. It is not.

### Steps to reproduce

Upgrade to v3.5.8 from v3.5.7. The issue appears automatically.

**Comment by onairmarc** [comment]
![Screenshot_05-21-24_0314PM](https://github.com/awcodes/filament-curator/assets/50760632/f4c495c6-4058-432b-bd45-56b0578b5dc9)

**Comment by awcodes** [comment]
Rebuild your theme. `npm run build`

**Comment by awcodes** [comment]
Might need a `artisan filament:assets` first though.

**Comment by onairmarc** [comment]
I should have time this weekend to dive into this. Right now we're pinned at `v3.5.7` until I get time to debug.

**Comment by onairmarc** [comment]
I mistakenly published the curator views when I was trying something and forgot to delete them. I was conditionally showing details based on permissions. I guess there was some change between the version I published and the most recent updates. Deleting the views that shouldn't have been committed fixed this issue.

This was most definitely a skill issue on my end.
