### ISSUE TITLE
S3 Uploads: Image source not readable

### ISSUE THREAD

**Issue by SanthoshSivan-Dev** [awcodes/filament-curator#491]
### Filament Version

v3.0.39

### Plugin Version

v3.0

### PHP Version

PHP 8.1.0

### Problem description

Attempting to upload media to S3 using the CuratorPicker component throws the following exception.

Intervention \ Image \ Exception \ NotReadableException - Image source not readable

The visibility of this media is set to private however the bucket was also made public just to ensure there are no issues with access. I'm no AWS expert so it's possible I've missed something super obvious, so apologies if that is the case.

In the linked reproduction repo the following steps in order were taken

1. Created a new Laravel App, installed latest Filament Panels v3 (stable)
2. Setup an S3 bucket & IAM user
3. Attach AmazonS3FullAccess permissions to the user, implement basic policy on bucket (see below)
4. Generated aws keys, added to .env
5. Added a simple Blog model with title and content
6. composer require awcodes/filament-curator & php artisan curator:install & npm install -D cropperjs
7. Generated a filament theme, imported the css mentioned in the documentation and updated tailwind.config.js
8. Included plugin in AdminPanelProvider
9. Generated a BlogResource and added CuratorPicker & FileUpload to the schema

![Screenshot from 2024-05-27 15-06-12](https://github.com/awcodes/filament-curator/assets/86248110/ec98ac17-3170-4025-9f6c-e7f58ae3beee)

### Expected behavior

Upload should not throw the exception. Expect the newly uploaded image to appear in the "media library" output for selection.

### Steps to reproduce

1. create new project, install dependencies
2. Login as user, go to Media
3. Attempt to create a new Media model via the form, observe exception
4. Navigate to Blogs, edit an existing blog
5. Upload a file to the S3 Upload input, wait for upload, save
6. Observe no issues
7. Add media, attempt to upload images via the right-hand side
8. Observe exception

**Comment by bytemewebdev** [comment]
I am experiencing this too today, I deployed my project via Laravel Vapor. When uploading using the FileUpload input, there are no issues. But when using the CuratorPicker I receive an error. 

<img width="1517" alt="Screenshot 2024-09-11 at 11 48 50 PM" src="https://github.com/user-attachments/assets/2f52dba6-aea0-4e70-afdb-cd7d4a6cfc85">
