### ISSUE TITLE
Glide 403 signature exception

### ISSUE THREAD

**Issue by jaymeh** [awcodes/filament-curator#500]
### Filament Version

v3.2.92

### Plugin Version

v3.6.2

### PHP Version

PHP 8.2.18

### Problem description

When viewing the media library none of my thumbnails are being displayed and I have 404 error being shown in the Browser.

![CleanShot 2024-06-23 at 16 10 49@2x](https://github.com/awcodes/filament-curator/assets/18261676/570f400f-3255-4b18-93f7-a5dbcf8dcd33)

It seems that when debugging the show function of the media controller I am getting a 403 error back due to the signature from Glide being invalidated.

![CleanShot 2024-06-23 at 16 14 06](https://github.com/awcodes/filament-curator/assets/18261676/a0f72f5b-1e70-476f-ace1-4c443b9c65ff)

Upon checking the request all function, it seems to return back an empty array even though I can see the correct details in the request URI.

![CleanShot 2024-06-23 at 16 15 01](https://github.com/awcodes/filament-curator/assets/18261676/38c466de-26fe-45cf-9849-6965ad18fa9d)

![CleanShot 2024-06-23 at 16 15 27](https://github.com/awcodes/filament-curator/assets/18261676/cd47bfb0-6222-4ccb-b92b-cab61a73fe69)

I'm using the latest version of Laravel 11 as of right now (v11.11.1).

### Expected behavior

When viewing the media library page, I'd expect to see the media library items being generated using Glide.

### Steps to reproduce

Setup Laravel Project Using DDEV
Install Laravel 11.11.1
Install Filament Panels and setup
Setup new theme and follow instructions from guide
Setup Curator with default settings, initialise plugin and add cropper etc to theme
Upload a file, then visit the main screen to see an image 404'ing in the browser.

### Reproduction repository

https://github.com/jaymeh/filament-curator

**Comment by awcodes** [comment]
My best guess here is a server misconfiguration. The requestUri looks correct to me.

**Comment by jaymeh** [comment]
ok, I've been using this environment for a few years and I've not seen issues like this before. I'll try to see if I can replicate this using Laravel Sail.

Thanks

**Comment by awcodes** [comment]
It could be that the server is trying to serve these directly as images instead of letting it run through the php controller. Some nginx server will serve static assets like this directly based on the file extension. Could be something to do with that.

**Comment by xalabama** [comment]
I also think it could be a problem with you nginx configuration. 

There was already a discussion about that sounds like your problem: https://github.com/awcodes/filament-curator/discussions/333

You can try to add this location configuration inside your nginx config:

```
location ^~ /curator {
    try_files $uri $uri/ /index.php?$query_string;
}
```

**Comment by jaymeh** [comment]
These are really useful points. I was using NGINX with my local environment but switching to Apache has resolved the issue.

Thanks @awcodes @xalabama !
