### ISSUE TITLE
Ver. 1.0.0+ breaks the close button for the Admin package database notifications slide-over

### ISSUE THREAD

**Issue by grahammtbr** [awcodes/filament-curator#51]
Like the title says, the close button (x) on the slide-over for database notifications (the bell in the top nav) becomes not clickable with Curator 1.0.0 and up installed. I rolled back to 0.7.7 and it works again on that version. 

No idea why (no console errors), I found it by trial and error by removing non-default composer packages one at a time.

This is on the latest version of Filament, 2.16.52 (also tried 2.16.51 to no avail).

**Comment by awcodes** [comment]
Interesting. They have nothing to do with each other. I'll look into it though. Thank you.

**Comment by grahammtbr** [comment]
I found it, in plugin.css you styled the built-in modal class:

`.filament-modal-content {
    position: relative;
}`

which then applies it to the notification slide-over model.

Changing it to something like,

`.filament-curator-modal-window .filament-modal-content {
    position: relative;
}`

seems to fix the issue.

**Comment by awcodes** [comment]
Thank you. I'll address it tomorrow.

**Comment by awcodes** [comment]
This should be resolved with v1.0.3.

Thanks.
