### ISSUE TITLE
Generate webp thumbnails

### ISSUE THREAD

**Issue by ldrshv** [awcodes/filament-curator#53]
Hi! Can I generate webp thumbnails when uploading pictures? And can I prevent the thumbnail size growing if the original picture size is smaller than the thumbnail size? 
Sorry for my English, translated it through DeepL))

**Comment by awcodes** [comment]
Currently these are not available. Have to figure out some other things first but I will make a note to make sure they are on the roadmap.

Thanks.

**Comment by howdu** [comment]
This is working well for us by update filament-curator.php config file sizes
```php
'sizes' => [
        'thumbnail' => ['width' => 200, 'height' => 200, 'format' => 'webp', 'quality' => 60],
        'small' => ['width' => 400, 'height' => null, 'format' => 'webp', 'quality' => 60],
        'medium' => ['width' => 640, 'height' => null, 'format' => 'webp', 'quality' => 80],
```

**Comment by awcodes** [comment]
Awesome. Currently working integrating Glide so you don't have to even implement manual thumbnails. They can be dynamically generated on the fly and cached for future delivery.
