### ISSUE TITLE
Broken interface with default filament theme

### ISSUE THREAD

**Issue by lotarbo** [awcodes/filament-curator#533]
### Filament Version

3.2.106

### Plugin Version

3.6.8 

### PHP Version

8.3.10

### Problem description

Hello. I installed filament and curator. I'm not using the bone theme, everything is default. But the interface looks broken
<img width="1350" alt="image" src="https://github.com/user-attachments/assets/edd4f895-3658-4c9c-9a15-c64691cffe6d">

### Expected behavior

I'd like to see a corrected interface

### Steps to reproduce

1. Install filament
2. composer require awcodes/filament-curator
3. php artisan curator:install
4. upload several pdf files

**Comment by awcodes** [comment]
You have to create a custom theme. It's covered in the plugins Readme.

**Comment by lotarbo** [comment]
Sorry, i just think i need this step only if i use custom theme in filament, not by default, sorry.
Only use curator with filament 2

**Comment by awcodes** [comment]
V2 should be fine out of the box. But v3 changed fundamentally on how plugins include styles.
