### ISSUE TITLE
We can only select multiple medias if one is already attached

### ISSUE THREAD

**Issue by MallauryGerard** [awcodes/filament-curator#536]
### Filament Version

3.2

### Plugin Version

3.6.9

### PHP Version

8.3

### Problem description

It is not possible to select several media if the model is blank.
The first image must be selected before selecting more images.

```
  CuratorPicker::make('photos_ids')
      ->label('')
      ->multiple()
      ->lazyLoad()
      ->directory($path)
      ->buttonLabel('Ajouter des photos')
      ->relationship('photos', 'id')
      ->orderColumn('order'),
```

### Expected behavior

We would be able to select multiple medias

### Steps to reproduce

Here is a video
![Recording 2024-09-02 at 11 44 17](https://github.com/user-attachments/assets/51048647-6446-4313-b94b-8fccaf0a1ae1)

**Comment by MallauryGerard** [comment]
Ok I just figured out that there is a configuration "multi_select_key". But that's strange both behaviors are different

**Comment by sjsiam** [comment]
> Ok I just figured out that there is a configuration "multi_select_key". But that's strange both behaviors are different

How did you fix it?

**Comment by JVariance** [comment]
@MallauryGerard I'd also like to know, how you fixed it :)

**Comment by Elangosurya1998** [comment]
> Ok I just figured out that there is a configuration "multi_select_key". But that's strange both behaviors are different

I would like to know how you fixed this :)

**Comment by jhiguerasa** [comment]
@MallauryGerard  Any solution? Thx
