### ISSUE TITLE
Awcodes\Curator\is_media_resizable(): Argument #1 ($type) must be of type string, null given

### ISSUE THREAD

**Issue by achmadjp7** [awcodes/filament-curator#538]
### Filament Version

v3.2

### Plugin Version

v3.6

### PHP Version

PHP 8.3.9

### Problem description

Awcodes\Curator\is_media_resizable(): Argument #1 ($type) must be of type string, null given, called in D:\PROJECTS\artea-website\storage\framework\views\8932f504d102906e356dc389201de488.php on line 61 
![gambar](https://github.com/user-attachments/assets/a2e4f8de-3880-40b7-a610-5d37aa46abfb)

![gambar](https://github.com/user-attachments/assets/d5434ec3-90e9-43db-b3c2-cf24941f9571)

![gambar](https://github.com/user-attachments/assets/2e9bf9db-710b-49ca-b5e8-4c1188c75620)

> <?php

return [
    'accepted_file_types' => [
        'image/jpeg',
        'image/png',
        'image/webp',
        'image/svg+xml',
        'application/pdf',
    ],
    'cloud_disks' => [
        's3',
        'cloudinary',
        'imgix',
    ],
    'curation_formats' => [
        'jpg',
        'jpeg',
        'webp',
        'png',
        'avif',
    ],
    'curation_presets' => [
        \Awcodes\Curator\Curations\ThumbnailPreset::class,
    ],
    'directory' => 'media',
    'disk' => env('FILAMENT_FILESYSTEM_DISK', 'public'),
    'glide' => [
        'server' => \Awcodes\Curator\Glide\DefaultServerFactory::class,
        'fallbacks' => [],
        'route_path' => 'curator',
    ],
    'image_crop_aspect_ratio' => null,
    'image_resize_mode' => null,
    'image_resize_target_height' => null,
    'image_resize_target_width' => null,
    'is_limited_to_directory' => false,
    'is_tenant_aware' => true,
    'tenant_ownership_relationship_name' => 'tenant',
    'max_size' => 5000,
    'model' => \Awcodes\Curator\Models\Media::class,
    'min_size' => 0,
    'path_generator' => null,
    'resources' => [
        'label' => 'Media',
        'plural_label' => 'Media',
        'navigation_group' => null,
        'cluster' => null,
        'navigation_label' => 'Media',
        'navigation_icon' => 'heroicon-o-photo',
        'navigation_sort' => null,
        'navigation_count_badge' => false,
        'resource' => \Awcodes\Curator\Resources\MediaResource::class,
    ],
    'should_preserve_filenames' => false,
    'should_register_navigation' => true,
    'should_check_exists' => true,
    'visibility' => 'public',
    'tabs' => [
        'display_curation' => true,
        'display_upload_new' => true,
    ],
    'multi_select_key' => 'metaKey',
    'table' => [
        'layout' => 'grid',
    ],
];

### Expected behavior

Curator is working properly

### Steps to reproduce

I just following installation on this url: https://filamentphp.com/plugins/awcodes-curator#installation

**Comment by awcodes** [comment]
defaultListView() should be 'grid' or 'list'. The readme just shows the options. It's not meant to just be copy pasted as is.

**Comment by achmadjp7** [comment]
> defaultListView() should be 'grid' or 'list'. The readme just shows the options. It's not meant to just be copy pasted as is.

Thank you
