### ISSUE TITLE
Intervention \ Image \ Exception \ NotReadableException - Image source not readable

### ISSUE THREAD

**Issue by bytemewebdev** [awcodes/filament-curator#539]
### Filament Version

v3.2

### Plugin Version

v3.6

### PHP Version

PHP 8.2

### Problem description

_Creating a new issue because [#491](https://github.com/awcodes/filament-curator/issues/491) was closed without any explanation._

Attempting to upload media to S3 using the `CuratorPicker` or `Media Resource` component throws the following exception.

`Intervention \ Image \ Exception \ NotReadableException - Image source not readable`

But uploading images using `FileUpload` has no errors

Project is deployed using Laravel Vapor.

<img width="1517" alt="Screenshot 2024-09-11 at 11 48 50 PM" src="https://github.com/user-attachments/assets/2f52dba6-aea0-4e70-afdb-cd7d4a6cfc85">

### Expected behavior

Upload should not throw the exception. Expect the newly uploaded image to appear in the "media library" output for selection.

### Steps to reproduce

1. Deploy project to Vapor
2. Upload images via the `CuratorPicker` or `Media Resource`
3. `Intervention \ Image \ Exception \ NotReadableException - Image source not readable`

**Comment by awcodes** [comment]
It can't read the file, my best guess is that you might need to publish the livewire config and set the temp directory to also use s3. Or there could be a bucket permissions issue where it can't read the file.

**Comment by bytemewebdev** [comment]
I have already tried setting the livewire config tmp file upload to s3, but still the error exists.

**Comment by awcodes** [comment]
My guess is a permission on the bucket then. Did you set the visibility for curator to be private either in the config or on the picker?

**Comment by bytemewebdev** [comment]
I haven't touched any of that.

**Comment by bytemewebdev** [comment]
> My guess is a permission on the bucket then. Did you set the visibility for curator to be private either in the config or on the picker?

Using `FileUpload` input field is working fine btw.

**Comment by bytemewebdev** [comment]
I have found the solution

`config('livewire.temporary_file_upload.directory')` default value is `livewire-tmp`. When I tried to access it directly from S3 I got access denied, and by doing some google searches, the solution is 

`'directory' => 'tmp'`

**Comment by lyrihkaesa** [comment]
## This is cause: 
```php
if (in_array(config('livewire.temporary_file_upload.disk'), config('curator.cloud_disks')) && config('livewire.temporary_file_upload.directory') !== null) {}
```

https://github.com/awcodes/filament-curator/blob/67c448a520ed93ca4fd5c6de9f1e8152d22a6c96/src/Components/Forms/Uploader.php#L103-L107

## Solution with custom s3 config like minio
And if, i am need custom `s3`, example `minio`, i need rewrite config:
`config('livewire.temporary_file_upload.disk')` and `config('curator.cloud_disks')`.
Like this:
- `.env`
```env
FILAMENT_FILESYSTEM_DISK=minio
```

- `config/livewire.php`
```php
 'temporary_file_upload' => [
        'disk' => env('FILAMENT_FILESYSTEM_DISK', 'public'),        // Example: 'local', 's3'              | Default: 'default'
        'rules' => null,       // Example: ['file', 'mimes:png,jpg']  | Default: ['required', 'file', 'max:12288'] (12MB)
        'directory' => 'livewire-tmp',   // Example: 'tmp'                      | Default: 'livewire-tmp'
        'middleware' => null,  // Example: 'throttle:5,1'             | Default: 'throttle:60,1'
        'preview_mimes' => [   
               // Supported file types for temporary pre-signed file URLs...
        ],
        'max_upload_time' => 5, // Max duration (in minutes) before an upload is invalidated...
    ],
```

- `config/curator.php`
```php
 'cloud_disks' => [
        's3',
        'cloudinary',
        'imgix',
        'minio', // here custom s3 cloud disk
    ],
```
