### ISSUE TITLE
Navigation Count doesn't work when made active

### ISSUE THREAD

**Issue by KujengaDigital99** [awcodes/filament-curator#544]
### Filament Version

v3.2

### Plugin Version

v3.6

### PHP Version

8.2

### Problem description

![Screenshot 2024-10-17 125157](https://github.com/user-attachments/assets/a83d7973-95bd-4230-84d2-f13218f895b5)

When I disable ->navigationGroup('Content') = The media navigation appears on the left, with the ->navigationCountBadge() showing as well

### Expected behavior

How ever when I uncomment ->navigationGroup('Content') = Menu disappears entirely

![image](https://github.com/user-attachments/assets/861c1bc3-db1c-427e-88c0-739cd59a3507)

### Steps to reproduce

1.  I created a working Model for the Media to be linked
2. I use CuratorPicker::make()
3. used the >NavigationCount and it broke

**Comment by awcodes** [comment]
Your code is working fine in demo app. Can you provide a reproduction repo?

![Screenshot 2024-10-18 at 10 51 33 AM](https://github.com/user-attachments/assets/f06d5e10-45ab-4fd9-bdc9-dc661064cd42)

```php
->plugins([
    CuratorPlugin::make()
        ->navigationGroup('Content')
        ->navigationCountBadge()
        ->navigationSort(3),
])
```
