### ISSUE TITLE
Getting 401 Error code while uploading file

### ISSUE THREAD

**Issue by kstmostofa** [awcodes/filament-curator#550]
### Filament Version

v3.2

### Plugin Version

v3.6

### PHP Version

PHP 8.2

### Problem description

It's working fine with my local setup. but the issue occurs in my production server. in my production server using docker and nginx

![curator error](https://github.com/user-attachments/assets/0892859f-6133-4844-951e-117e4504b45f)

### Expected behavior

file must be uploaded

### Steps to reproduce

file not uploading

**Comment by awcodes** [comment]
Sounds like a permissions issue on your server. If it's working fine on local then I'm not sure this is an issue with the plugin.

**Comment by kstmostofa** [comment]
> Sounds like a permissions issue on your server. If it's working fine on local then I'm not sure this is an issue with the plugin.

I am running docker with an Nginx proxy. but its works fine when using without docker
