### ISSUE TITLE
wrong src path in Preview for List View

### ISSUE THREAD

**Issue by capetrel** [awcodes/filament-curator#551]
### Filament Version

3.2.115

### Plugin Version

3.5

### PHP Version

8.3

### Problem description

The preview don't work in List View mode :
![wrong-src-path-preview-list-view](https://github.com/user-attachments/assets/27faff62-626c-4c8a-ba48-d31e352e2164)

### Expected behavior

See preview image

### Steps to reproduce

Switch between Grid View / List View

**Comment by awcodes** [comment]
Have published any of the views? List view is working fine in my demo app.

![Screenshot 2024-11-05 at 11 02 39 AM](https://github.com/user-attachments/assets/2687dbfe-b128-4962-9cb6-b7da57821754)
