### ISSUE TITLE
Intervention\Image — Unsupported image type image/avif.

### ISSUE THREAD

**Issue by DanielSpravtsev** [awcodes/filament-curator#552]
### Filament Version

last

### Plugin Version

last

### PHP Version

8.3

### Problem description

Hey @awcodes,

I’m currently working on automatically re-uploading all images within Tiptap to my media storage, where I’m manually handling storage and creating entries in Curator Media. However, I’ve encountered this issue:

```Intervention\Image\Exception\NotReadableException  Unsupported image type image/avif. GD driver is only able to decode JPG, PNG, GIF, BMP or WebP files.```

Is there a way to upgrade Curator to use the 3.* branch of intervention/image to support .avif images? (Reference: [.avif support](https://github.com/Intervention/image/issues/1229))

### Expected behavior

.

### Steps to reproduce

.

**Comment by awcodes** [comment]
At the moment I can't upgrade intervention until glide does. It is already merged into glide v3 but I haven't seen any indication as to when it will be released.
