### ISSUE TITLE
max size config not working properly 

### ISSUE THREAD

**Issue by afsharmn** [awcodes/filament-curator#564]
### Filament Version

^3.2

### Plugin Version

^3.6

### PHP Version

^8.2

### Problem description

i changed `'max_size' => 5000,` to `'max_size' => 100000,` in config file but it doesnt let me to upload files bigger than 12288 kilobytes.
![Screenshot 2024-12-14 153308](https://github.com/user-attachments/assets/e4be5c2c-67c9-4be5-9ba8-73cf8362570b)

i tried bigger file like 200MB but i faced error : The data.file.f8eaf7d2-255e-4193-8ff0-a987b642bd21 failed to upload.

### Expected behavior

I expect it to work as expected :(

### Steps to reproduce

--------------

**Comment by afsharmn** [comment]
i found this option in livewire config . should i change that or curator plugin responsible for change that ?



```
    'temporary_file_upload' => [
        'disk' => null,        // Example: 'local', 's3'              | Default: 'default'
        'rules' => null,       // Example: ['file', 'mimes:png,jpg']  | Default: ['required', 'file', 'max:12288'] (12MB)
        'directory' => null,   // Example: 'tmp'                      | Default: 'livewire-tmp'
        'middleware' => null,  // Example: 'throttle:5,1'             | Default: 'throttle:60,1'
        'preview_mimes' => [   // Supported file types for temporary pre-signed file URLs...
            'png', 'gif', 'bmp', 'svg', 'wav', 'mp4',
            'mov', 'avi', 'wmv', 'mp3', 'm4a',
            'jpg', 'jpeg', 'mpga', 'webp', 'wma',
        ],
        'max_upload_time' => 5, // Max duration (in minutes) before an upload is invalidated...
        'cleanup' => true, // Should cleanup temporary uploads older than 24 hrs...
    ],
```

Default: ['required', 'file', 'max:12288']

**Comment by awcodes** [comment]
Yea. There's 2 points where this can matter that aren't directly associated with the plugin. Livewire has a max setting based on its config and there's also the php ini setting too. Both of those need to be modified at their respective levels to be able to upload files larger than 12mb.
