### ISSUE TITLE
Is croping possible?

### ISSUE THREAD

**Issue by Dontorpedo** [awcodes/filament-curator#57]
Hello,

I would like to crop some images when i generate different sizes instead of resize, is croping possible with this package?

maybe an optinal cropping when width and height are filled?

thank you

**Comment by awcodes** [comment]
There was some discussion about this on Discord. Currently, the answer is no, but it is something i'm hoping to bring to the plugin soon. Still working out the API and best way forward.

**Comment by Wulfheart** [comment]
@awcodes Is it in the plugin now as this issue has been closed as completed?

**Comment by awcodes** [comment]
Cropping is handled via curations. Curator is a bit of a mind shift from what we're used to in the past. You don't need specific sizes for each image you upload. The glider component will generate sizes dynamically on an as need basis and curations can be used to offset that for specific images when needed. This keeps your server from getting bloated with thumbnails, etc that will never actually get rendered.
