### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'image'

### ISSUE THREAD

**Issue by Dontorpedo** [awcodes/filament-curator#67]
Hello, i use the curator on 2 websites, first is running well, on the second when i use the Media field, i have this error when i try to save the record, when i enter the id of the image manually in the database it works again.. 

how can i solve this?

`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'image' at row 1 (SQL: update `blog_posts` set `image` = {"id":140,"public_id":"media\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac","filename":"media\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac.jpg","ext":"jpg","type":"image\/jpeg","alt":null,"title":null,"description":null,"caption":null,"width":1920,"height":1030,"disk":"public","directory":"media","size":150547,"created_at":"2022-12-23T18:17:46.000000Z","updated_at":"2022-12-23T18:17:46.000000Z","url":"https:\/\/vietnamholiday.org\/storage\/media\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac.jpg","thumbnail_url":"https:\/\/vietnamholiday.org\/storage\/media\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac-thumbnail.jpg","medium_url":"https:\/\/vietnamholiday.org\/storage\/media\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac-medium.jpg","large_url":"https:\/\/vietnamholiday.org\/storage\/media\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac-large.jpg","size_for_humans":"147 KiB","hasSizes":true}, `blog_posts`.`updated_at` = 2023-01-07 09:08:20 where `id` = 19) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'image' at row 1 (SQL: update `blog_posts` set `image` = {\"id\":140,\"public_id\":\"media\\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac\",\"filename\":\"media\\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac.jpg\",\"ext\":\"jpg\",\"type\":\"image\\/jpeg\",\"alt\":null,\"title\":null,\"description\":null,\"caption\":null,\"width\":1920,\"height\":1030,\"disk\":\"public\",\"directory\":\"media\",\"size\":150547,\"created_at\":\"2022-12-23T18:17:46.000000Z\",\"updated_at\":\"2022-12-23T18:17:46.000000Z\",\"url\":\"https:\\/\\/vietnamholiday.org\\/storage\\/media\\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac.jpg\",\"thumbnail_url\":\"https:\\/\\/vietnamholiday.org\\/storage\\/media\\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac-thumbnail.jpg\",\"medium_url\":\"https:\\/\\/vietnamholiday.org\\/storage\\/media\\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac-medium.jpg\",\"large_url\":\"https:\\/\\/vietnamholiday.org\\/storage\\/media\\/d23a7716-c7cc-44a0-b3d8-beb631ee91ac-large.jpg\",\"size_for_humans\":\"147 KiB\",\"hasSizes\":true}, `blog_posts`.`updated_at` = 2023-01-07 09:08:20 where `id` = 19) at /home/ploi/vietnamholiday.org/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)`

**Comment by awcodes** [comment]
This should be saving as a foreign id. There was a bug in the previous version. Please make sure you are on the latest version and you have setup your relationship correctly.
