### ISSUE TITLE
Image preview not working on media page

### ISSUE THREAD

**Issue by schroeder-hesel** [awcodes/filament-curator#87]
Hello,

the image preview on the media page is not working on my installation.

![image](https://user-images.githubusercontent.com/107101263/215453282-30af9c53-9f6b-4d5a-9f04-da03e4da459e.png)

I temporarily fixed it by setting "source_path_prefix" in  /src/Http/Controllers/MediaController.php(line 42) to an empty string. 

Not working:
`$server = ServerFactory::create([
            'response' => new LaravelResponseFactory(app('request')),
            'source' => $filesystem->getDriver(),
            'source_path_prefix' => 'public',
            'cache' => $filesystem->getDriver(),
            'cache_path_prefix' => '.cache',
            'base_url' => 'curator',
]);`

Working:
`$server = ServerFactory::create([
            'response' => new LaravelResponseFactory(app('request')),
            'source' => $filesystem->getDriver(),
            'source_path_prefix' => '',
            'cache' => $filesystem->getDriver(),
            'cache_path_prefix' => '.cache',
            'base_url' => 'curator',
]);`

It would be nice if this can be set with a setting.

I am using version 2.0.9.

**Comment by awcodes** [comment]
This is a glide thing. I'll see about exposing it as an option. Check your logs too, it could be a simple server misconfiguation too.
